title: DBSmasher Corner
description: Thoughts, stories and ideas
author: Silvia Botros
author_email: silviamikhail@gmail.com
github_username: silviabotros
gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
# paginate: nil
# paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

theme: jekyll-theme-slate
