title: dbsmasher corner
description: Thoughts, stories and ideas
author: Silvia Botros
author_email: silviamikhail@gmail.com
github_username: silviabotros
gems:
  - jekyll-paginate-v2
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
# paginate: nil
# paginate_path: nil

# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 20
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# Old jekyll-paginate pagination logic
#   Uncomment thew two entries below to demonstrate how this new gem
#   retains backwards compatibility with the old pagination logic
paginate: 50
paginate_path: "/legacy/page:num/"

theme: jekyll-theme-midnight
